Exercise 1

In the code cell below, define a variable n with value n = 5. Then:

(i) Use the function hilbert from SciPy's scipy.linalg module to define A to be the Hilbert matrix A of dimension n.

(ii) Compute A^{-1} using the function np.linalg.inv.

(iii) Use the function np.eye to define the identity matrix $I$ of dimension $n$.

(iv) Compute $I - A^{-1}A$. Is it zero? How does the error compare to machine epsilon? (The command np.finfo(float).eps returns the value of machine epsilon.)

(v) Repeat (i--iv) for $n = 10$ and $n = 15$. Does the increase in the computed values of $I - A^{-1}A$ surprise you?

Hilbert matrices are examples of so-called ill-conditioned matrices, which we will learn more about later. Generally speaking, ill-conditioned matrices are notoriously difficult to work with numerically, and even small rounding errors have a large effect on computed results.

In [1]:
import numpy as np
from scipy.linalg import hilbert
#hilbert matrix : 5*5
A = hilbert(5)
print(np.linalg.inv(A))

[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]


In [2]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
Ainv = np.linalg.inv(A)
print(I-Ainv*A)

[[-2.4000e+01  1.5000e+02 -3.5000e+02  3.5000e+02 -1.2600e+02]
 [ 1.5000e+02 -1.5990e+03  4.7250e+03 -5.3760e+03  2.1000e+03]
 [-3.5000e+02  4.7250e+03 -1.5875e+04  1.9600e+04 -8.1000e+03]
 [ 3.5000e+02 -5.3760e+03  1.9600e+04 -2.5599e+04  1.1025e+04]
 [-1.2600e+02  2.1000e+03 -8.1000e+03  1.1025e+04 -4.8990e+03]]


In [14]:
n=15
A1 = hilbert(n)
I1 = np.eye(n)
A1inv = np.linalg.inv(A1)
print(I1-A1inv*A1)

[[-1.52807409e+02  5.90369755e+03 -9.88661271e+04  8.98557115e+05
  -4.94670227e+06  1.74909713e+07 -4.07963236e+07  6.27500371e+07
  -6.16399158e+07  3.57738632e+07 -1.16271361e+07  6.14640887e+06
  -7.68627780e+06  4.80832999e+06 -1.07869630e+06]
 [ 5.90245013e+03 -4.05882679e+05  8.67903268e+06 -9.06964629e+07
   5.48769892e+08 -2.08607839e+09  5.17557070e+09 -8.43510247e+09
   8.76772477e+09 -5.26990397e+09  1.31275410e+09  3.55126820e+07
   2.72179483e+08 -3.31878817e+08  9.28694397e+07]
 [-9.87933654e+04  8.67457787e+06 -2.13176574e+08  2.44569214e+09
  -1.58753609e+10  6.39593351e+10 -1.67182428e+11  2.86441129e+11
  -3.12367024e+11  1.92650206e+11 -3.36914578e+10 -3.41709375e+10
   2.02494703e+10 -1.23390350e+09 -1.02012096e+09]
 [ 8.96935941e+05 -9.05593698e+07  2.44341308e+09 -3.00567663e+10
   2.06482402e+11 -8.74104875e+11  2.39206314e+12 -4.28316260e+12
   4.86417631e+12 -3.04496147e+12  2.84491621e+11  1.07660265e+12
  -8.06182729e+11  2.34560884e+11 -2.22623200e+10]
 [-4

In [15]:
n=10
A1 = hilbert(n)
I1 = np.eye(n)
A1inv = np.linalg.inv(A1)
print(I1-A1inv*A1)

[[-9.89965762e+01  2.47485203e+03 -2.63978983e+04  1.50135668e+05
  -5.04449304e+05  1.05092470e+06 -1.37262379e+06  1.09380100e+06
  -4.86130471e+05  9.23642393e+04]
 [ 2.47485208e+03 -1.08890478e+05  1.47001386e+06 -9.51251393e+06
   3.46807148e+07 -7.64385283e+07  1.04040641e+08 -8.55597686e+07
   3.89829774e+07 -7.55712042e+06]
 [-2.63978996e+04  1.47001391e+06 -2.25791843e+07  1.58540836e+08
  -6.11510604e+08  1.40455566e+09 -1.97291943e+09  1.66328519e+09
  -7.73218726e+08  1.52402643e+08]
 [ 1.50135681e+05 -9.51251449e+06  1.58540841e+08 -1.17772561e+09
   4.73388395e+09 -1.12210168e+10  1.61582136e+10 -1.38989151e+10
   6.56939378e+09 -1.31301224e+09]
 [-5.04449367e+05  3.46807179e+07 -6.11510639e+08  4.73388408e+09
  -1.96368009e+10  4.77173213e+10 -7.01079628e+10  6.13145612e+10
  -2.93874113e+10  5.94374289e+09]
 [ 1.05092487e+06 -7.64385375e+07  1.40455578e+09 -1.12210174e+10
   4.77173225e+10 -1.18307298e+11  1.76730511e+11 -1.56733239e+11
   7.60175732e+10 -1.55330199e+10

In the code cell below, define a variable n with value $n = 50$. Then:

(i) Use the function np.random.rand to define A to be a random matrix $A$ of dimension $n$.

(ii) Using the function time.time, find the time required to compute $A^{-1}$ using the function np.linalg.inv.

(iii) Use the method .format to format a string which reports the dimension of $A$ and the time required to compute $A^{-1}$, and print out the string.

In [24]:
import numpy as np
import time

n=50
A = np.random.rand(n,n)
print(A)

[[0.49205974 0.54420913 0.19637647 ... 0.45777551 0.29988975 0.01672294]
 [0.69308262 0.43739258 0.36032255 ... 0.12372269 0.99680149 0.74836353]
 [0.01439581 0.68327219 0.51383611 ... 0.4733032  0.94994235 0.93532424]
 ...
 [0.25667    0.03991112 0.49215191 ... 0.00270784 0.23321774 0.36848709]
 [0.56833882 0.00247763 0.98176436 ... 0.33498948 0.53599569 0.09738784]
 [0.04841666 0.92514274 0.00876988 ... 0.36303443 0.28316912 0.35625572]]


In [25]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0.99604478  1.28933594 -2.04298306 ... -0.54081889 -1.91124683
   0.0419743 ]
 [-1.20041791 -1.64937495  1.66676817 ...  0.08737393  2.46712394
  -0.7209625 ]
 [-1.02117887 -2.16715582  3.60664252 ...  0.14831626  4.15525473
   0.05535053]
 ...
 [ 0.20645966  0.91314328 -1.28142032 ... -0.58032535 -1.24478992
  -0.34740895]
 [-0.94666581 -0.38555519  0.61866504 ... -0.23728836  1.65018316
  -0.24155452]
 [-0.58034544  0.22222011 -0.2004097  ... -0.87621963 -0.65515407
  -0.6152499 ]]


In [27]:
time = time.time()
print(time)

1568796247.0316641


In [28]:
import numpy as np
import time

n=50
A = np.random.rand(n,n)
t1 = time.time()
Ainv = np.linalg.inv(A)
t2 = time.time()
t=t2-t1
print(t)

0.001779317855834961


In [29]:
n = 3
k = 5
s = 'The value of n is {}, and the value of k is {}.'.format(n, k)
print(s)

The value of n is 3, and the value of k is 5.


Use the method .format to format a string which reports the dimension of $A$ and the time required to compute $A^{-1}$, and print out the string.

In [30]:
n = 50
s = 'the dimension of A is {} and the time required to compute inverse A is {}.'.format(n, t)
print(s)

the dimension of A is 50 and the time required to compute inverse A is 0.001779317855834961.


In the code cell below, load the matrix $A$ from the file bcsstk08.npy using the function np.load, and store it in a variable A. Then:

(i) Identify the dimension $n$ of the matrix $A$.

(ii) Create a variable x to represent a vector $x \in \mathbb{R}^n$, all of whose entries are $1$.

(iii) Compute the vector $b = Ax$ with the command b = A @ x.

(iv) Find and report the time required to solve $Ax=b$:

by computing $A^{-1}$ as Ainv and then forming Ainv @ b, and
by using the function np.linalg.solve.
(v) How do the times for the two approaches compare?

In [42]:
import numpy as np
import time

A = np.load('bcsstk08.npy')
print(A)

[[1.48435200e+06 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.06553179e+08 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.90420605e+09 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.07848000e+04
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  2.58256643e+05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 2.58256643e+05]]


In [49]:
n = np.shape(A)
a = A.shape[0]
print(n)
print(a)

(1074, 1074)
1074


In [51]:
x = np.ones(a)
print(x)

[1. 1. 1. ... 1. 1. 1.]


In [52]:
b = A*x
print(b)

[[1.48435200e+06 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.06553179e+08 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.90420605e+09 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.07848000e+04
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  2.58256643e+05 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 2.58256643e+05]]


Ainv = np.linalg.inv(A)
x = np.linalg.solve(Ainv,b)
print(x)

In [62]:
t1 = time.time()
Ainv = np.linalg.inv(A)
x = np.linalg.solve(Ainv,b)
t2 = time.time()
b = A*x
t3= time.time()
t = t2-t1
tt = t3-t2
print(t)
print(tt)

0.14020609855651855
0.004969120025634766


In the cell below:

(i) Write a for loop to repeat (i--iii) from Exercise 2, for $n=50 \times 2^k$ with $k=1, 2, \dots, 8$.

(ii) Determine the ratio between the computation time for $k$ and the computation time for $k-1$, for $k=2, \dots, 8$. How does it behave?


In the code cell below, define a variable n with value $n = 50$. Then:

(i) Use the function np.random.rand to define A to be a random matrix $A$ of dimension $n$.

(ii) Using the function time.time, find the time required to compute $A^{-1}$ using the function np.linalg.inv.

(iii) Use the method .format to format a string which reports the dimension of $A$ and the time required to compute $A^{-1}$, and print out the string.

In [64]:
import numpy as np
import time

for i in range(1,8):
    n = 50*2**i
    A = np.random.rand(n,n)
    t1 = time.time()
    Ainv = np.linalg.inv(A)
    t2 = time.time()
    t = t2-t1
    s = 'the dimension of A is {} and the time required to compute inverse A is {}.'.format(n, t)
    print(s)

the dimension of A is 100 and the time required to compute inverse A is 733.5915951728821.
the dimension of A is 200 and the time required to compute inverse A is 733.5958020687103.
the dimension of A is 400 and the time required to compute inverse A is 733.611120223999.
the dimension of A is 800 and the time required to compute inverse A is 733.6544771194458.
the dimension of A is 1600 and the time required to compute inverse A is 733.9167020320892.
the dimension of A is 3200 and the time required to compute inverse A is 735.80597615242.
the dimension of A is 6400 and the time required to compute inverse A is 747.0929222106934.


In [65]:
import numpy as np
import time

for i in range(1,8):
    n = 50*2**i
    n2 = 50*2**i-1
    A = np.random.rand(n,n)
    t1 = time.time()
    Ainv = np.linalg.inv(A)
    t2 = time.time()
    t = t2-t1
    B = np.random.rand(n2,n2)
    t3 = time.time()
    tt = t3-t2
    ratio = t/tt
    print(ratio)
    

151.0
2.5385111182726394
2.8650273224043716
4.345290637618556
5.6770595287774315
13.05027145843066
18.770656777396507
