# MATH10098: Numerical Linear Algebra - Workshop week 3

Please note that on Notable, computational times might be a bit erratic. For comparing computational times, it is best to run the notebook on a desktop or laptop using e.g. Anaconda.

### Exercise 1: Errors and Residuals (Easy)

In the code cell below, set a variable `n` with value $n=50$. Use `np.random.rand` to define `A` to be a random matrix $A$ of dimension $n$. Then:

(i) Create a variable `xsol` to represent a vector $x^{\ast} \in \mathbb{R}^n$, all of whose entries are $1$.

(ii) Compute `b = A @ xsol` to represent the vector $b=Ax^{\ast}$.

(iii) Use `np.linalg.solve` to compute `x`, the *computed* solution of $Ax=b$.

(iv) Compute the $1$, $2$, and $\infty$ norms of the residual vector `r = A @ x - b`. This can be done using the function `np.linalg.norm`. Note that `np.inf` is used to denote $\infty$.

(v) Compute the $1$, $2$, and $\infty$ norms of the solution error `e = x - xsol`.

(vi) Both the residual `r` and the error `e` measure how close the computed solution `x` is to the exact solution `xsol`. Report the norms of the residual and solution error. How do the norms of `r` and `e` compare?

Now repeat parts (i-vi) with `n = 50` and `A = hilbert(n)` (using the function `hilbert` from SciPy's `scipy.linalg` module), where `A` represents the Hilbert matrix $A$ of dimension $n$. Do you notice a difference?

In [6]:
import numpy as np
from scipy.linalg import hilbert

n = 50
A = np.random.rand(n,n)
xsol = np.ones([50,1])
b = A @ xsol
x = np.linalg.solve(A,b)
r = A @ x - b
nr1 = np.linalg.norm(r,1)
nr2 = np.linalg.norm(r,2)
nrInf = np.linalg.norm(r,np.inf)
e = x - xsol
ne1 = np.linalg.norm(e,1)
ne2 = np.linalg.norm(e,2)
neInf = np.linalg.norm(e,np.inf)
print(nr1, ne1)
print(nr2, ne2)
print(nrInf, neInf)


# add code here

2.0961010704922955e-13 1.4430678874077785e-12
3.8755530747763045e-14 2.470016939383297e-13
1.4210854715202004e-14 8.959499808725013e-14


In [7]:
import numpy as np
from scipy.linalg import hilbert

n = 50
A = hilbert(n)
xsol = np.ones([50,1])
b = A @ xsol
x = np.linalg.solve(A,b)
r = A @ x - b
nr1 = np.linalg.norm(r,1)
nr2 = np.linalg.norm(r,2)
nrInf = np.linalg.norm(r,np.inf)
e = x - xsol
ne1 = np.linalg.norm(e,1)
ne2 = np.linalg.norm(e,2)
neInf = np.linalg.norm(e,np.inf)
print(nr1, ne1)
print(nr2, ne2)
print(nrInf, neInf)

1.6986412276764895e-14 730.7913995534402
3.3435965876850375e-15 142.30732397696178
1.3322676295501878e-15 54.72242674615239


---

### Exercise 2: LU factorisation (Standard)

In the code cell below:

(i) Write a Python function `LU` to implement Algorithm LU from the lecture notes. As stated in the algorithm, your function should take a single input variable `A`, representing a matrix $A \in \mathbb{R}^{n\times n}$, and return two variables, `L` and `U`, representing the matrices $L, U \in \mathbb{R}^{n\times n}$ in the LU factorisation of $A$, such that $A = LU$.

(ii) Test your function on the following example:

$$
A =
\begin{bmatrix}
2&1&1 \\ 4&3&3 \\ 8&7&9
\end{bmatrix}
=
\begin{bmatrix}
1&0&0 \\ 2&1&0 \\ 4&3&1
\end{bmatrix}
\begin{bmatrix}
2&1&1 \\ 0&1&1 \\ 0&0&2
\end{bmatrix}
= LU.
$$

In [58]:
import numpy as np

A = np.array([[2,1,1],[4,3,3],[8,7,9]])

def LU(A):
    n = 3
    L = np.eye(n,n)
    U = A
    for k in range(0,n-1):
        for j in range(k+1,n):
            L[j,k] = U[j, k]/U[k,k]
            U[j, k:n-1] = U[j, k:n-1] - L[j,k] * U[k, k:n-1]
            

    # add code here
    
    return L, U

In [35]:
LU(A)

(array([[1., 0., 0.],
        [2., 1., 0.],
        [4., 3., 1.]]), array([[2, 1, 1],
        [0, 1, 3],
        [0, 0, 9]]))

In [27]:
A = np.array([[2,1,1],[4,3,3],[8,7,9]])
U = A
L = np.eye(3,3)
L[1,0] = U[1,0]/U[0,0]
print(L[1,0])
print(L)

2.0
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]


---

### Back Substitution

The function `BS` below solves the equation $Ux=y$, for a non-singular, upper triangular matrix $U\in \mathbb{R}^{n\times n}$ and a vector $y \in \mathbb{R}^n$, using Algorithm BS from the lecture notes. 

In [59]:
import numpy as np

def BS(U, y):
    n = U.shape[0]
    x = np.zeros(n)
    
    for j in range(n-1, -1, -1):
        x[j] = (y[j] - U[j, j+1:] @ x[j+1:]) / U[j, j]
    
    return x

***Comments:*** Note that for `j = n - 1`, the vectors `U[j, j+1:]` and `x[j+1:]` are empty. This corresponds to the fact that the sum in Line 2 of Algorithm BS does not contain any terms for $j=n$.

In [67]:
A = np.zeros((3, 7))
print(A.shape)
print(A.shape[0])
n = A.shape[0]
x = np.zeros(n)
print(x)

(3, 7)
3
[0. 0. 0.]


---

### Exercise 3: Forward Substitution (Standard)

(i) Write down (in pseudocode) the forward substitution algorithm, i.e. write an algorithm that solves the equation $Ly=b$, for a non-singular, lower triangular matrix $L\in \mathbb{R}^{n\times n}$ and a vector $b \in \mathbb{R}^n$. (This should be similar to Algorithm BS from the lecture notes.)

(ii) What is the computational cost of the forward substitution algorithm?

(iii) In the cell below, write a function `FS` to implement your forward substitution algorithm. Your function should take two input arguments, `L` and `b`, and return one output variable, `y`.

In [60]:
import numpy as np

def FS(L,b):
    n = L.shape[0]
    y = np.zeros(n)
    
    for i in range(0,n):
        y[i] = b[i] - (L[i, :i]@y[:i])
        
    return y
    
# add code here

In [55]:
L = np.array([[1,0,0],[2,1,0],[3,4,1]])
b = np.array([4,10,24])

FS(L,b)

array([4., 2., 4.])

In [46]:
L = np.array([[1,0,0],[2,1,0],[3,4,1]])
b = np.array([4,10,24])
y = np.zeros(3)

y[0] = b[0] - (L[0, :0]@y[:0])
y[1] = b[1] - (L[1, :1]@y[:1])
y[2] = b[2] - (L[2, :2]@y[:2])
print(y[0],y[1],y[2])


4.0 2.0 4.0


---

### Exercise 4: Gaussian Elimination (Easy)

(i) In the code cell below, write a function `GE` which performs Gaussian elimination, using your functions `LU`, `FS`, and `BS`. The function `GE` should take two input arguments, `A` and `b`, and return one variable `x`, representing the solution $x \in \mathbb{R}^n$ of $Ax=b$.

*Note: recall that you do not need to copy/paste your previous functions into the cell below -- simply run the cells in which you have written the functions to store them in memory and make them available to* `GE`.

(ii) Test your function `GE` with the following values:

$$
A =
\begin{bmatrix}
2&1&1 \\ 4&3&3 \\ 8&7&9
\end{bmatrix}\, , \quad
b =
\begin{bmatrix}
4 \\ 10 \\ 24
\end{bmatrix}.
$$

(iii) Determine the elapsed time and time ratio when using your function `GE` to solve $Ax=b$ using a random matrix $A$ and random vector $b$ of dimension $n = 50 \times 2^k$ for $k=1, 2, \dots, 5$. Are the results as you expected?

(Please note that on Notable, the computational times might be a bit erratic. For comparing computational times, it is best to run the notebook on a desktop or laptop using e.g. Anaconda.)

In [82]:
import numpy as np
import time

def GE(A,b):
    LU(A)
    FS(L,b)
    BS(U,y)
    return x

# add code here

In [74]:
A = np.array([[2,1,1],[4,3,3],[8,7,9]])
b = ([4,10,24])

GE(A,b)

array([0., 0., 0.])

In [78]:
import numpy as np
import time

for k in range(1,6):
    n = 50*(2**k)
    t = time.time()
    A = np.random.rand(n,n)
    b = np.random.rand(n)
    GE(A,b)
    t1 = time.time()
    tt = t1-t
    print(tt)


0.0005400180816650391
0.001682281494140625
0.004945039749145508
0.013046026229858398
0.041506052017211914


---

### Exercise 5: Efficiency of Gaussian Elimination (Easy)

In Algorithm LU, consider replacing Line 5 by

$$
5': \quad
(u_{j1}, \dots, u_{jn}) = (u_{j1}, \dots, u_{jn}) - l_{jk}(u_{k1}, \dots, u_{kn})
$$

(i) Explain why this change does not affect the computed matrices $L$ and $U$.

(ii) Explain why this change does affect the computational cost of Algorithm LU. What is the cost of the modified algorithm?

(iii) Modify your code above to implement this modification. Do you see a difference in the computational times to solve a system $Ax=b$, between Algorithm GE and the modified version with the LU factorisation modified as above?

In [81]:
import numpy as np

def LU(A):
    n = 3
    L = np.eye(n,n)
    U = A
    for k in range(0,n-1):
        for j in range(k+1,n):
            L[j,k] = U[j, k]/U[k,k]
            U[j, 0:n-1] = U[j, 0:n-1] - L[j,k] * U[k, 1:n-1]
            

    # add code here
    
    return L, U

In [80]:
A = np.array([[2,1,1],[4,3,3],[8,7,9]])

LU(A)

(array([[1., 0., 0.],
        [2., 1., 0.],
        [4., 3., 1.]]), array([[2, 1, 1],
        [2, 1, 3],
        [1, 0, 9]]))

In [83]:
A = np.array([[2,1,1],[4,3,3],[8,7,9]])
b = ([4,10,24])


GE(A,b)

array([0., 0., 0.])

---

### Exercise 6: Block LU factorisation (Difficult)

A *divide-and-conquer* method aims to solve a large problem *recursively*. The main problem is subdivided (*branched*) into 2 smaller problems, and these problems are each themselves subdivided -- until we end up with many simpler problems, each solvable by a direct method. The solution to the main problem is finally obtained by combining the solutions of the small problems.

For example, the following function computes $x^n, x \in \mathbb{R}, n \in \mathbb{N}$ relatively efficiently using a divide-and-conquer approach, by further taking advantage of the problem symmetry.

In [11]:
def power(x, n):
    '''
    Compute x^n using a divide-and-conquer method.
    x^n is written as x^n = x^(2m + k), where k may be 0 or 1,
    which allows to only have to compute 1 branch at every depth level.
    '''
    # Reached the last level
    if n == 1:
        return x
    
    # Write x^n = x^(2m + k), where k = 0 or 1
    m = n // 2
    k = n - 2*m
    
    # Compute x^m recursively
    xm = power(x, m)
    
    # Separate even and odd cases
    if k == 0:
        return xm * xm
    else:
        return x * xm * xm
    
print(power(2, 10))

1024


Let $A \in \mathbb{R}^{n\times n}$, where $n = 2^k$ for some $k \in \mathbb{N}$, be a non-singular matrix. The LU factorisation of $A$ can be written in block form as

$$
\begin{bmatrix}
A_{11} & A_{12} \\
A_{21} & A_{22}
\end{bmatrix}
= A = LU =
\begin{bmatrix}
L_{11} & 0 \\
L_{21} & L_{22}
\end{bmatrix}
\begin{bmatrix}
U_{11} & U_{12} \\
0 & U_{22}
\end{bmatrix},
$$

where all the blocks are of size $\frac{n}{2} \times \frac{n}{2}$.

(i) Devise an algorithm DAC-LU, which uses a divide-and-conquer strategy for LU factorisation.

(ii) Write a function `DAC_LU` which computes the LU decomposition of a matrix $A$ using your algorithm.

(iii) For $n = 2^k$, with $k=6, \dots, 11$, generate a random matrix $A\in \mathbb{R}^{n\times n}$, and compute its LU decomposition using both `LU` and `DAC_LU` functions. Report the computation times obtained with both methods. What do you observe?

(iv) What is the cost of Algorithm DAC-LU?

Some tips to get you started:

* You may wish to modify your `FS` and/or `BS` functions in order to solve systems of the form $LY=B$ and/or $UX=Y$, respectively, where $X, Y, B \in \mathbb{R}^{n \times m}$.
* $XA=B \Leftrightarrow (XA)^T = B^T$.
* The function [`numpy.allclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html) may be useful to check that `DAC_LU` is computing the correct matrices.

In [ ]:
import numpy as np
import time

# add code here